name: Bug report
description: Report a reproducible problem with the theme
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue and expected behavior.
      placeholder: A clear and concise description.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS / Node.js / package manager / browser.
      placeholder: Windows 11, Node 22, npm 10, Chrome 131
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste command output or stack traces if available.
      render: shell
